version: "3.8"

services:
    frontend:
        build:
            context: ./content-generator-client
        ports:
            - "3000:3000"
        depends_on:
            - backend

    backend:
        build:
            context: ./Server
        ports:
            - "8000:8000"
        env_file:
            - ./Server/.env
        depends_on:
            - mongo
        environment:
            - MONGO_URI=mongodb://mongo:27017/content-generator

    mongo:
        image: mongo:latest
        ports:
            - "27017:27017"
        volumes:
            - mongo_data:/data/db

volumes:
    mongo_data:
        driver: local
